name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"
change-template: "- $TITLE (#$NUMBER) @$AUTHOR"
change-title-escapes: '\<*_&'
categories:
  - title: "ðŸ”¥ BREAKING CHANGES"
    labels:
      - "breaking-change"
  - title: "ðŸš€ Features"
    labels:
      - "enhancement"
  - title: "ðŸ› Bug Fixes"
    labels:
      - "bug-fix"
  - title: "ðŸ‘· Chores"
    labels:
      - "chore"
  - title: "âš¡ï¸ Deprecations"
    labels:
      - "deprecation"
  - title: "â¬†ï¸ Dependencies Upgraded"
    labels:
      - "dependency"
exclude-labels:
  - "skip-changelog"
replacers:
  # https://github.com/release-drafter/release-drafter/issues/569#issuecomment-645938155
  - search: '(?:and )?@dependabot(?:\[bot\])?,?'
    replace: ""
version-resolver:
  major:
    labels:
      - "major"
  minor:
    labels:
      - "minor"
  patch:
    labels:
      - "patch"
  default: patch
exclude-contributors:
  - "dependabot"
autolabeler:
  # labels to help with version determination
  # if you want to play around with the regex here
  # I will suggest doing so on https://regex101.com/
  # it provides good explanation what the regex is doing
  # If that is not enough, ask chatgpt for help,
  # and then go back to playing with regex on regex101.com
  - label: "patch"
    title:
      # matches in format of "fix: ..."
      # or "fix(scope): ..."
      - '/^(?:fix|chore|docs|doc|refactor|test|deprecated)(?:\((?:[^)]+)\))?:\s.*/i'
  - label: "minor"
    title:
      # matches in format of "feat: ..."
      # or "feat(scope): ..."
      - '/^(?:feat|feature)(?:\((?:[^)]+)\))?:\s.*/i'
  - label: "major"
    title:
      # matches in format of "fix!: ..."
      # or "fix!(scope): ..."
      # or "fix(scope)!: ..."
      - '/^(?:feat|feature|fix|chore|docs|doc|refactor|test|deprecated)(?:!(?:\((?:[^)]+)\))|(?:\((?:[^)]+)\))!|!):\s.*/i'
    body:
      - "/BREAKING CHANGE:/"
  # labels to help with changelog grouping
  - label: "dependency"
    title:
      - "/^Bump/" # Dependency update PR by depandabot
  - label: "chore"
    title:
      - '/^(?:docs|doc|chore|refactor|test)(?:\((?:[^)]+)\))?:\s.*/i'
  - label: "enhancements"
    title:
      - '/^(?:feat|feature)(?:\((?:[^)]+)\))?:\s.*/i'
  - label: "bug-fix"
    title:
      - '/^fix(?:\((?:[^)]+)\))?:\s.*/i'
  - label: "deprecation"
    title:
      - '/^deprecated(?:\((?:[^)]+)\))?:\s.*/i'
  - label: "breaking-change"
    title:
      - '/^(?:feat|feature|fix|chore|docs|doc|refactor|test|deprecated)(?:!(?:\((?:[^)]+)\))|(?:\((?:[^)]+)\))!|!):\s.*/i'
    body:
      - "/BREAKING CHANGE:/"
template: |
  ## What's Changed
  $CHANGES
